In [325]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [326]:
df=pd.read_csv('train.csv')

In [327]:
df.head()

pet_id           issue_date         listing_date  condition  \
0  ANSL_69903  2016-07-10 00:00:00  2016-09-21 16:25:00        2.0   
1  ANSL_66892  2013-11-21 00:00:00  2018-12-27 17:47:00        1.0   
2  ANSL_69750  2014-09-28 00:00:00  2016-10-19 08:24:00        NaN   
3  ANSL_71623  2016-12-31 00:00:00  2019-01-25 18:30:00        1.0   
4  ANSL_57969  2017-09-28 00:00:00  2017-11-19 09:38:00        2.0   

    color_type  length(m)  height(cm)  X1  X2  breed_category  pet_category  
0  Brown Tabby       0.80        7.78  13   9             0.0             1  
1        White       0.72       14.19  13   9             0.0             2  
2        Brown       0.15       40.90  15   4             2.0             4  
3        White       0.62       17.82   0   1             0.0             2  
4        Black       0.50       11.06  18   4             0.0             1

In [328]:
df.drop(columns=['pet_id','issue_date','listing_date'],inplace=True)

In [329]:
df.head()

condition   color_type  length(m)  height(cm)  X1  X2  breed_category  \
0        2.0  Brown Tabby       0.80        7.78  13   9             0.0   
1        1.0        White       0.72       14.19  13   9             0.0   
2        NaN        Brown       0.15       40.90  15   4             2.0   
3        1.0        White       0.62       17.82   0   1             0.0   
4        2.0        Black       0.50       11.06  18   4             0.0   

   pet_category  
0             1  
1             2  
2             4  
3             2  
4             1

In [330]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18834 entries, 0 to 18833
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   condition       17357 non-null  float64
 1   color_type      18834 non-null  object 
 2   length(m)       18834 non-null  float64
 3   height(cm)      18834 non-null  float64
 4   X1              18834 non-null  int64  
 5   X2              18834 non-null  int64  
 6   breed_category  18834 non-null  float64
 7   pet_category    18834 non-null  int64  
dtypes: float64(4), int64(3), object(1)
memory usage: 1.1+ MB


In [331]:
cond_median=df['condition'].median()

In [332]:
cond_median

1.0

In [333]:
df['condition'].fillna(cond_median,inplace=True)

In [334]:
df.head()

condition   color_type  length(m)  height(cm)  X1  X2  breed_category  \
0        2.0  Brown Tabby       0.80        7.78  13   9             0.0   
1        1.0        White       0.72       14.19  13   9             0.0   
2        1.0        Brown       0.15       40.90  15   4             2.0   
3        1.0        White       0.62       17.82   0   1             0.0   
4        2.0        Black       0.50       11.06  18   4             0.0   

   pet_category  
0             1  
1             2  
2             4  
3             2  
4             1

In [335]:
df['pet_category'].value_counts()

2    10621
1     7184
4      941
0       88
Name: pet_category, dtype: int64

In [336]:
from sklearn.preprocessing import LabelEncoder

label_encoder=LabelEncoder()

df['color']=label_encoder.fit_transform(df['color_type'])

In [337]:
df.head()

condition   color_type  length(m)  height(cm)  X1  X2  breed_category  \
0        2.0  Brown Tabby       0.80        7.78  13   9             0.0   
1        1.0        White       0.72       14.19  13   9             0.0   
2        1.0        Brown       0.15       40.90  15   4             2.0   
3        1.0        White       0.62       17.82   0   1             0.0   
4        2.0        Black       0.50       11.06  18   4             0.0   

   pet_category  color  
0             1     18  
1             2     53  
2             4     15  
3             2     53  
4             1      2

In [338]:
df=df.drop(columns=['color_type'])

In [339]:
df.head()

condition  length(m)  height(cm)  X1  X2  breed_category  pet_category  \
0        2.0       0.80        7.78  13   9             0.0             1   
1        1.0       0.72       14.19  13   9             0.0             2   
2        1.0       0.15       40.90  15   4             2.0             4   
3        1.0       0.62       17.82   0   1             0.0             2   
4        2.0       0.50       11.06  18   4             0.0             1   

   color  
0     18  
1     53  
2     15  
3     53  
4      2

In [343]:
s=0
for i in df['length(m)']:
    if i==0:
        s+=1
print(s)

93


In [344]:
len_med=df['length(m)'].median()
len_med

0.5

In [345]:
for i in range(df['length(m)'].shape[0]):
    if df['length(m)'][i]==0:
        df['length(m)']=len_med

In [346]:
s=0
for i in df['length(m)']:
    if i==0:
        s+=1
print(s)

0


In [347]:
from sklearn.preprocessing import StandardScaler

In [348]:
sc=StandardScaler()

In [349]:
y1=df['pet_category'].values
y2=df['breed_category'].values

In [350]:
y1,y2

(array([1, 2, 4, ..., 1, 2, 2], dtype=int64),
 array([0., 0., 2., ..., 1., 1., 1.]))

In [351]:
X=df.drop(columns=['pet_category','breed_category'])

In [352]:
X.head()

condition  length(m)  height(cm)  X1  X2  color
0        2.0        0.5        7.78  13   9     18
1        1.0        0.5       14.19  13   9     53
2        1.0        0.5       40.90  15   4     15
3        1.0        0.5       17.82   0   1     53
4        2.0        0.5       11.06  18   4      2

In [353]:
X=sc.fit_transform(X)

In [354]:
X[0]

array([ 1.49606758,  0.        , -1.51072853,  1.16101336,  1.25727915,
       -0.33762349])

In [355]:
X

array([[ 1.49606758,  0.        , -1.51072853,  1.16101336,  1.25727915,
        -0.33762349],
       [ 0.14517407,  0.        , -1.01838767,  1.16101336,  1.25727915,
         1.46357614],
       [ 0.14517407,  0.        ,  1.03316059,  1.46532585, -0.16411631,
        -0.49201203],
       ...,
       [-1.20571944,  0.        ,  0.05231929,  1.16101336,  1.25727915,
        -0.1317721 ],
       [-1.20571944,  0.        ,  1.33424892,  1.16101336,  1.25727915,
         1.20626191],
       [-1.20571944,  0.        ,  0.76433173, -0.81701778, -1.01695359,
        -0.49201203]])

In [356]:
df['pet_category'].value_counts()

2    10621
1     7184
4      941
0       88
Name: pet_category, dtype: int64

# ann model

In [357]:
import keras

from keras.models import Sequential
from keras.layers import Dense


model = Sequential()
model.add(Dense(16, input_dim=6, activation='relu'))
model.add(Dense(32,  activation='relu'))
model.add(Dense(64,  activation='relu'))
model.add(Dense(32,  activation='relu'))
model.add(Dense(5,  activation='sigmoid'))

model.summary()


Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_55 (Dense)             (None, 16)                112       
_________________________________________________________________
dense_56 (Dense)             (None, 32)                544       
_________________________________________________________________
dense_57 (Dense)             (None, 64)                2112      
_________________________________________________________________
dense_58 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_59 (Dense)             (None, 5)                 165       
Total params: 5,013
Trainable params: 5,013
Non-trainable params: 0
_________________________________________________________________


In [358]:
from keras.utils import to_categorical

In [359]:
y1=to_categorical(y1)
y2=to_categorical(y2)

In [360]:
y1,y2

(array([[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        ...,
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.]], dtype=float32),
 array([[1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        ...,
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]], dtype=float32))

In [362]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Train model
history = model.fit(X, y1, nb_epoch=50, batch_size=30,  verbose=1)

C:\Users\singh\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until


Epoch 1/50
18834/18834 [==============================] - 1s 41us/step - loss: 0.1840 - accuracy: 0.9148
Epoch 2/50
18834/18834 [==============================] - 1s 30us/step - loss: 0.1817 - accuracy: 0.9160
Epoch 3/50
18834/18834 [==============================] - 1s 30us/step - loss: 0.1811 - accuracy: 0.9158
Epoch 4/50
18834/18834 [==============================] - 1s 32us/step - loss: 0.1811 - accuracy: 0.9158
Epoch 5/50
18834/18834 [==============================] - 1s 29us/step - loss: 0.1795 - accuracy: 0.9169
Epoch 6/50
18834/18834 [==============================] - 1s 30us/step - loss: 0.1792 - accuracy: 0.9175
Epoch 7/50
18834/18834 [==============================] - 1s 29us/step - loss: 0.1775 - accuracy: 0.9180
Epoch 8/50
18834/18834 [==============================] - 1s 29us/step - loss: 0.1767 - accuracy: 0.9191
Epoch 9/50
18834/18834 [==============================] - 1s 28us/step - loss: 0.1752 - accuracy: 0.9201
Epoch 10/50
18834/18834 [==============================

In [363]:
test=pd.read_csv('test.csv')

In [364]:
test.shape

(8072, 9)

In [365]:
test.head()

pet_id           issue_date         listing_date  condition  \
0  ANSL_75005  2005-08-17 00:00:00  2017-09-07 15:35:00        0.0   
1  ANSL_76663  2018-11-15 00:00:00  2019-05-08 17:24:00        1.0   
2  ANSL_58259  2012-10-11 00:00:00  2018-04-02 16:51:00        1.0   
3  ANSL_67171  2015-02-13 00:00:00  2018-04-06 07:25:00        1.0   
4  ANSL_72871  2017-01-18 00:00:00  2018-04-26 13:42:00        1.0   

     color_type  length(m)  height(cm)  X1  X2  
0         Black       0.87       42.73   0   7  
1  Orange Tabby       0.06        6.71   0   1  
2         Black       0.24       41.21   0   7  
3         Black       0.29        8.46   7   1  
4         Brown       0.71       30.92   0   7

In [366]:
test.drop(columns=['pet_id','issue_date','listing_date'],inplace=True)

In [367]:
test.head()

condition    color_type  length(m)  height(cm)  X1  X2
0        0.0         Black       0.87       42.73   0   7
1        1.0  Orange Tabby       0.06        6.71   0   1
2        1.0         Black       0.24       41.21   0   7
3        1.0         Black       0.29        8.46   7   1
4        1.0         Brown       0.71       30.92   0   7

In [368]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8072 entries, 0 to 8071
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   condition   7453 non-null   float64
 1   color_type  8072 non-null   object 
 2   length(m)   8072 non-null   float64
 3   height(cm)  8072 non-null   float64
 4   X1          8072 non-null   int64  
 5   X2          8072 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 378.5+ KB


In [369]:
test['condition'].fillna(cond_median,inplace=True)

In [370]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8072 entries, 0 to 8071
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   condition   8072 non-null   float64
 1   color_type  8072 non-null   object 
 2   length(m)   8072 non-null   float64
 3   height(cm)  8072 non-null   float64
 4   X1          8072 non-null   int64  
 5   X2          8072 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 378.5+ KB


In [371]:
test['color']=label_encoder.transform(test['color_type'])

In [372]:
test.drop(columns=['color_type'],inplace=True)

In [373]:
test.head()

condition  length(m)  height(cm)  X1  X2  color
0        0.0       0.87       42.73   0   7      2
1        1.0       0.06        6.71   0   1     38
2        1.0       0.24       41.21   0   7      2
3        1.0       0.29        8.46   7   1      2
4        1.0       0.71       30.92   0   7     15

In [374]:
for i in range(test['length(m)'].shape[0]):
    if test['length(m)'][i]==0:
        test['length(m)']=len_med

In [375]:
s=0
for i in test['length(m)']:
    if i==0:
        s+=1
print(s)

0


In [376]:
test=sc.transform(test)

In [377]:
test

array([[-1.20571944,  0.        ,  1.17371968, -0.81701778,  0.68872097,
        -1.16102904],
       [ 0.14517407,  0.        , -1.59291335, -0.81701778, -1.01695359,
         0.69163344],
       [ 0.14517407,  0.        ,  1.05697115, -0.81701778,  0.68872097,
        -1.16102904],
       ...,
       [-1.20571944,  0.        ,  0.748202  , -0.81701778,  0.68872097,
        -1.16102904],
       [ 0.14517407,  0.        , -0.27795617, -0.81701778, -0.7326745 ,
        -1.16102904],
       [-1.20571944,  0.        , -0.22572657, -0.81701778, -1.01695359,
        -1.16102904]])

In [378]:
predict_out1=model.predict_classes(test)

In [379]:
predict_out1[:1000]

array([2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 4, 1, 2,
       1, 2, 2, 2, 2, 4, 2, 2, 1, 4, 1, 2, 2, 4, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 4, 2, 1, 2, 2, 1, 2, 2, 2, 2,
       1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 4, 2, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2,
       2, 1, 2, 4, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2,
       1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2,
       2, 4, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1,
       2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 4, 1, 2, 2, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2,

In [380]:
model2 = Sequential()
model2.add(Dense(16, input_dim=6, activation='relu'))
model2.add(Dense(32,  activation='relu'))
model2.add(Dense(64,  activation='relu'))
model2.add(Dense(32,  activation='relu'))
model2.add(Dense(3,  activation='sigmoid'))
model2.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_60 (Dense)             (None, 16)                112       
_________________________________________________________________
dense_61 (Dense)             (None, 32)                544       
_________________________________________________________________
dense_62 (Dense)             (None, 64)                2112      
_________________________________________________________________
dense_63 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_64 (Dense)             (None, 3)                 99        
Total params: 4,947
Trainable params: 4,947
Non-trainable params: 0
_________________________________________________________________


In [381]:
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Train model
history = model2.fit(X, y2, nb_epoch=20, batch_size=30,  verbose=1)

C:\Users\singh\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until


Epoch 1/20
18834/18834 [==============================] - 1s 39us/step - loss: 0.2476 - accuracy: 0.8732
Epoch 2/20
18834/18834 [==============================] - 1s 36us/step - loss: 0.1822 - accuracy: 0.8958
Epoch 3/20
18834/18834 [==============================] - 1s 32us/step - loss: 0.1790 - accuracy: 0.8970
Epoch 4/20
18834/18834 [==============================] - 1s 30us/step - loss: 0.1751 - accuracy: 0.8985
Epoch 5/20
18834/18834 [==============================] - 1s 32us/step - loss: 0.1705 - accuracy: 0.8982
Epoch 6/20
18834/18834 [==============================] - 1s 35us/step - loss: 0.1671 - accuracy: 0.8992
Epoch 7/20
18834/18834 [==============================] - 1s 28us/step - loss: 0.1657 - accuracy: 0.9015
Epoch 8/20
18834/18834 [==============================] - 1s 30us/step - loss: 0.1649 - accuracy: 0.9014
Epoch 9/20
18834/18834 [==============================] - 1s 30us/step - loss: 0.1645 - accuracy: 0.9012
Epoch 10/20
18834/18834 [==============================

In [382]:
predict_out2=model2.predict_classes(test)

In [383]:
predict_out2[:1000]

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 2, 0, 0,
       0, 0, 1, 0, 1, 2, 1, 1, 1, 2, 1, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 2, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 2, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 2, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 1, 1,
       0, 1, 0, 1, 0, 2, 0, 0, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [384]:
test_data=pd.read_csv('test.csv')

In [385]:
test_id=test_data['pet_id']

In [386]:
test_id.values

array(['ANSL_75005', 'ANSL_76663', 'ANSL_58259', ..., 'ANSL_60034',
       'ANSL_58066', 'ANSL_69436'], dtype=object)

In [387]:
df=pd.DataFrame({'pet_id':test_id,'breed_category':predict_out2,'pet_category':predict_out1})

In [388]:
df

pet_id  breed_category  pet_category
0     ANSL_75005               1             2
1     ANSL_76663               0             1
2     ANSL_58259               0             2
3     ANSL_67171               0             1
4     ANSL_72871               0             2
...          ...             ...           ...
8067  ANSL_66809               1             2
8068  ANSL_59041               1             2
8069  ANSL_60034               1             2
8070  ANSL_58066               2             2
8071  ANSL_69436               1             2

[8072 rows x 3 columns]

In [389]:
df.to_csv('final.csv',index=False)